[package]
name = "schedule-thing"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.18"
num-bigint = {version = "0.4.3", features = ["serde"]}
serde = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
